--[[
	SoundConfig (ModuleScript)
	Location: ReplicatedStorage/Config/SoundConfig

	THE single place for every sound in CAUGHT ON CAMERA.

	How a sound id is resolved (first match wins):
	  1. entry.Ids          - individual uploaded variations ("rbxassetid://123", ...)
	  2. SoundConfig.Loops  - a dedicated seamless loop file (looped entries only)
	  3. SoundConfig.Banks  - one uploaded "sound bank" file containing many sounds;
	                          regions come from SoundBankLayout (generated by
	                          tools/sfx/generate_sfx.py together with assets/audio/)
	  4. entry.Fallback     - a built-in Roblox sound, pitched, so NOTHING is silent
	                          even before you upload any audio.

	All original sounds of the game live in just FOUR files
	(assets/audio/banks/*.ogg): upload them, paste the 4 ids below, done.
	(Alternative without editing code: set the attributes SoundBank_Equipment,
	SoundBank_Player, SoundBank_World and SoundBank_Loops on SoundService in
	Studio to the uploaded ids - they override the table below.)

	Every asset is preloaded with ContentProvider and verified at runtime; a
	missing or failed asset prints "[AudioService] Failed sound: <path>" and
	that sound falls back to the next source automatically. /soundtest (admin)
	and SETTINGS > AUDIO > TEST SOUND check the whole chain.

	Every entry is addressed by its path, e.g. "Camera.Shutter",
	"Flashlight.On", "EMF.Level5", "Player.Footstep.Metal",
	"Door.Security.Slam", "Anomaly.ListenerAttack".

	Entry fields
	  Ids           { "rbxassetid://..." }  explicit variations (optional)
	  Volume        base volume
	  Pitch         { min, max } random PlaybackSpeed multiplier (subtle variation)
	  VolumeJitter  +/- fraction of random volume variation
	  Group         SoundGroup: Music, Ambience, PlayerSFX, EquipmentSFX, AnomalySFX, Voice, Jumpscares, UI
	  Spatial       true = 3D positional (heard from its position), false = 2D
	  RollOff       { RollOffMinDistance, RollOffMaxDistance }
	  Occlusion     muffle when walls are between the listener and the sound
	  Noise         world noise intensity (0-1) when a PLAYER makes this sound
	  NoiseKind     what sound-sensitive anomalies "hear" (Shutter, Flash, Run, DoorSlam, ...)
	  Looped        loops until stopped
	  Fallback      { builtinId, playbackSpeed }
]]

local SoundConfig = {}

-- Paste the ids of the uploaded bank files from assets/audio/banks here
-- (see docs/SOUND_DESIGN.md). One upload covers dozens of sounds.
--   Equipment : Camera, Flashlight, EMF, Thermal, UV, NightVision, Equipment
--   Player    : footsteps, jumps/landings, doors, interactions
--   World     : anomalies, environment, UI
--   Loops     : every looping sound (ambience, music, hums, breathing)
SoundConfig.Banks = {
	Equipment = "", -- PLACEHOLDER: rbxassetid:// of assets/audio/banks/Equipment.ogg
	Player = "", -- PLACEHOLDER: rbxassetid:// of assets/audio/banks/Player.ogg
	World = "", -- PLACEHOLDER: rbxassetid:// of assets/audio/banks/World.ogg
	Loops = "", -- PLACEHOLDER: rbxassetid:// of assets/audio/banks/Loops.ogg
}

-- OPTIONAL: individual loop files (assets/audio/loops/*.ogg). Leave empty to
-- use the Loops bank; fill in only if you prefer separate loop uploads.
SoundConfig.Loops = {
	MallHum = "",
	RainSkylight = "",
	HVAC = "",
	ListenerBreath = "",
	FlashlightBuzz = "",
	UVHum = "",
	NightVisionHum = "",
	ThermalScan = "",
	MusicLobby = "",
	MusicTension = "",
	CarAlarm = "",
	StoreAlarm = "",
	TVStatic = "",
	EntityDrone = "",
}

-- Built-in Roblox content sounds (always available, used as fallbacks).
local B = {
	Click = "rbxasset://sounds/clickfast.wav",
	Ping = "rbxasset://sounds/electronicpingshort.wav",
	Step = "rbxasset://sounds/action_footsteps_plastic.mp3",
	Land = "rbxasset://sounds/action_jump_land.mp3",
	Jump = "rbxasset://sounds/action_jump.mp3",
	Splash = "rbxasset://sounds/impact_water.mp3",
	Swoosh = "rbxasset://sounds/swordslash.wav",
	Unsheath = "rbxasset://sounds/unsheath.wav",
	Groan = "rbxasset://sounds/uuhhh.mp3",
	Wind = "rbxasset://sounds/action_falling.mp3",
	Swim = "rbxasset://sounds/action_swim.mp3",
	GetUp = "rbxasset://sounds/action_get_up.mp3",
	Lunge = "rbxasset://sounds/swordlunge.wav",
}
SoundConfig.Builtin = B

---------------------------------------------------------------------------
-- Sound groups (mixer). Setting = the player setting that scales the group.
---------------------------------------------------------------------------
SoundConfig.Groups = {
	Master = { Parent = nil, Volume = 1, Setting = "MasterVolume" },
	Music = { Parent = "Master", Volume = 0.55, Setting = "MusicVolume" },
	Ambience = { Parent = "Master", Volume = 0.8, Setting = "AmbienceVolume" },
	PlayerSFX = { Parent = "Master", Volume = 1 },
	EquipmentSFX = { Parent = "Master", Volume = 1, Setting = "EquipmentVolume" },
	AnomalySFX = { Parent = "Master", Volume = 1 },
	Voice = { Parent = "Master", Volume = 1, Setting = "VoiceVolume" },
	Jumpscares = { Parent = "Master", Volume = 1, Setting = "JumpscareVolume" },
	UI = { Parent = "Master", Volume = 0.8 },
}
SoundConfig.GroupOrder = { "Master", "Music", "Ambience", "PlayerSFX", "EquipmentSFX", "AnomalySFX", "Voice", "Jumpscares", "UI" }

local function S(entry)
	entry.Ids = entry.Ids or {}
	entry.Volume = entry.Volume or 0.7
	entry.Pitch = entry.Pitch or { 0.96, 1.04 }
	entry.VolumeJitter = entry.VolumeJitter or 0.08
	entry.Group = entry.Group or "EquipmentSFX"
	if entry.Spatial == nil then
		entry.Spatial = true
	end
	entry.RollOff = entry.RollOff or { 6, 70 }
	if entry.Occlusion == nil then
		entry.Occlusion = entry.Spatial
	end
	return entry
end

---------------------------------------------------------------------------
-- CAMERA
---------------------------------------------------------------------------
SoundConfig.Camera = {
	Equip = S({ Volume = 0.55, Fallback = { B.Unsheath, 1.6 }, RollOff = { 4, 35 } }),
	Unequip = S({ Volume = 0.45, Fallback = { B.Unsheath, 1.2 }, RollOff = { 4, 30 } }),
	Shutter = S({ Volume = 0.9, Pitch = { 0.97, 1.03 }, Fallback = { B.Click, 0.85 }, RollOff = { 8, 90 }, Noise = 0.15, NoiseKind = "Shutter" }),
	Focus = S({ Volume = 0.25, Pitch = { 0.99, 1.01 }, Fallback = { B.Ping, 2.2 }, RollOff = { 3, 22 }, Noise = 0.04, NoiseKind = "Focus" }),
	FocusBroken = S({ Volume = 0.5, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.4 }, RollOff = { 4, 35 }, Noise = 0.08, NoiseKind = "Focus" }),
	ZoomIn = S({ Volume = 0.35, Fallback = { B.Swoosh, 2.4 }, RollOff = { 3, 20 } }),
	ZoomOut = S({ Volume = 0.35, Fallback = { B.Swoosh, 2 }, RollOff = { 3, 20 } }),
	LensMove = S({ Volume = 0.22, Pitch = { 0.9, 1.1 }, Fallback = { B.Swoosh, 3 }, RollOff = { 3, 18 } }),
	ButtonClick = S({ Volume = 0.35, Fallback = { B.Click, 1.6 }, RollOff = { 3, 18 } }),
	FlashCharge = S({ Volume = 0.25, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.5 }, RollOff = { 3, 22 } }),
	FlashTrigger = S({ Volume = 0.6, Fallback = { B.Click, 0.6 }, RollOff = { 6, 60 }, Noise = 0.1, NoiseKind = "Flash" }),
	BatteryLow = S({ Volume = 0.4, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.9 }, Spatial = false, Group = "UI" }),
	BatteryEmpty = S({ Volume = 0.5, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.55 }, Spatial = false, Group = "UI" }),
	CaptureSuccess = S({ Volume = 0.55, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.25 }, Spatial = false, Group = "UI" }),
	CaptureRare = S({ Volume = 0.75, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.7 }, Spatial = false, Group = "UI" }),
	Glitch = S({ Volume = 0.55, Pitch = { 0.8, 1.2 }, Fallback = { B.Click, 0.25 }, RollOff = { 4, 30 } }),
	Static = S({ Volume = 0.45, Pitch = { 0.9, 1.1 }, Fallback = { B.Click, 0.2 }, RollOff = { 4, 30 } }),
	Error = S({ Volume = 0.45, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.4 }, Spatial = false, Group = "UI" }),
}

---------------------------------------------------------------------------
-- FLASHLIGHT
---------------------------------------------------------------------------
SoundConfig.Flashlight = {
	Equip = S({ Volume = 0.45, Fallback = { B.Unsheath, 1.9 }, RollOff = { 4, 30 } }),
	Unequip = S({ Volume = 0.4, Fallback = { B.Unsheath, 1.5 }, RollOff = { 4, 30 } }),
	On = S({ Volume = 0.55, Fallback = { B.Click, 1.25 }, RollOff = { 4, 40 }, Noise = 0.05, NoiseKind = "FlashlightClick" }),
	Off = S({ Volume = 0.5, Fallback = { B.Click, 1.1 }, RollOff = { 4, 40 }, Noise = 0.05, NoiseKind = "FlashlightClick" }),
	ButtonClick = S({ Volume = 0.45, Fallback = { B.Click, 1.4 }, RollOff = { 4, 35 }, Noise = 0.05, NoiseKind = "FlashlightClick" }),
	BatteryInsert = S({ Volume = 0.5, Fallback = { B.Click, 0.7 }, RollOff = { 4, 30 }, Noise = 0.04, NoiseKind = "Interaction" }),
	BatteryRemove = S({ Volume = 0.45, Fallback = { B.Click, 0.8 }, RollOff = { 4, 30 } }),
	LowBattery = S({ Volume = 0.35, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.8 }, Spatial = false, Group = "UI" }),
	Buzz = S({ Volume = 0.3, Looped = true, Loop = "FlashlightBuzz", Fallback = { B.Click, 0.12 }, RollOff = { 3, 25 } }),
	Flicker = S({ Volume = 0.4, Pitch = { 0.85, 1.15 }, Fallback = { B.Click, 2.2 }, RollOff = { 4, 35 }, Noise = 0.15, NoiseKind = "FlashlightMalfunction" }),
	ElectricalFailure = S({ Volume = 0.6, Fallback = { B.Click, 0.3 }, RollOff = { 5, 50 }, Noise = 0.15, NoiseKind = "FlashlightMalfunction" }),
	BulbFailure = S({ Volume = 0.55, Fallback = { B.Click, 0.45 }, RollOff = { 5, 45 }, Noise = 0.3, NoiseKind = "FlashlightMalfunction" }),
	Interference = S({ Volume = 0.35, Pitch = { 0.8, 1.2 }, Fallback = { B.Click, 0.18 }, RollOff = { 3, 25 } }),
}

---------------------------------------------------------------------------
-- EMF DETECTOR (levels 1-5 have distinct pitch; beep rate is set by EquipmentConfig)
---------------------------------------------------------------------------
SoundConfig.EMF = {
	Equip = S({ Volume = 0.45, Fallback = { B.Unsheath, 2 }, RollOff = { 4, 30 } }),
	Unequip = S({ Volume = 0.4, Fallback = { B.Unsheath, 1.6 }, RollOff = { 4, 30 } }),
	PowerOn = S({ Volume = 0.4, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.5 }, RollOff = { 3, 30 } }),
	PowerOff = S({ Volume = 0.35, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.1 }, RollOff = { 3, 30 } }),
	Level1 = S({ Volume = 0.25, Pitch = { 1, 1 }, VolumeJitter = 0, Fallback = { B.Ping, 1.6 }, RollOff = { 3, 30 } }),
	Level2 = S({ Volume = 0.3, Pitch = { 1, 1 }, VolumeJitter = 0, Fallback = { B.Ping, 1.8 }, RollOff = { 3, 32 } }),
	Level3 = S({ Volume = 0.35, Pitch = { 1, 1 }, VolumeJitter = 0, Fallback = { B.Ping, 2 }, RollOff = { 3, 35 } }),
	Level4 = S({ Volume = 0.42, Pitch = { 1, 1 }, VolumeJitter = 0, Fallback = { B.Ping, 2.25 }, RollOff = { 4, 38 } }),
	Level5 = S({ Volume = 0.5, Pitch = { 1, 1 }, VolumeJitter = 0, Fallback = { B.Ping, 2.5 }, RollOff = { 4, 42 } }),
	Distort = S({ Volume = 0.45, Pitch = { 0.7, 1.3 }, Fallback = { B.Click, 0.22 }, RollOff = { 4, 35 } }),
	BrokenBeep = S({ Volume = 0.45, Pitch = { 0.6, 1.4 }, Fallback = { B.Ping, 1.2 }, RollOff = { 4, 35 } }),
}

---------------------------------------------------------------------------
-- THERMAL SCANNER
---------------------------------------------------------------------------
SoundConfig.Thermal = {
	Equip = S({ Volume = 0.45, Fallback = { B.Unsheath, 1.8 }, RollOff = { 4, 30 } }),
	Unequip = S({ Volume = 0.4, Fallback = { B.Unsheath, 1.4 }, RollOff = { 4, 30 } }),
	Activate = S({ Volume = 0.45, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.9 }, RollOff = { 3, 30 } }),
	Shutdown = S({ Volume = 0.4, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.6 }, RollOff = { 3, 30 } }),
	ScanLoop = S({ Volume = 0.12, Looped = true, Loop = "ThermalScan", Fallback = { B.Click, 0.1 }, RollOff = { 2, 16 } }),
	TargetLock = S({ Volume = 0.4, Pitch = { 1, 1 }, Fallback = { B.Ping, 2.4 }, RollOff = { 3, 25 } }),
	HeatDetected = S({ Volume = 0.45, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.75 }, RollOff = { 3, 28 } }),
	BatteryWarning = S({ Volume = 0.35, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.8 }, Spatial = false, Group = "UI" }),
	Interference = S({ Volume = 0.35, Pitch = { 0.8, 1.2 }, Fallback = { B.Click, 0.2 }, RollOff = { 3, 25 } }),
}

---------------------------------------------------------------------------
-- UV LIGHT (lower, "purple" electrical character vs the normal flashlight)
---------------------------------------------------------------------------
SoundConfig.UV = {
	Equip = S({ Volume = 0.45, Fallback = { B.Unsheath, 1.7 }, RollOff = { 4, 30 } }),
	Unequip = S({ Volume = 0.4, Fallback = { B.Unsheath, 1.3 }, RollOff = { 4, 30 } }),
	On = S({ Volume = 0.5, Fallback = { B.Click, 0.95 }, RollOff = { 4, 40 }, Noise = 0.05, NoiseKind = "FlashlightClick" }),
	Off = S({ Volume = 0.45, Fallback = { B.Click, 0.85 }, RollOff = { 4, 40 }, Noise = 0.05, NoiseKind = "FlashlightClick" }),
	Hum = S({ Volume = 0.18, Looped = true, Loop = "UVHum", Fallback = { B.Click, 0.08 }, RollOff = { 2, 18 } }),
	BatteryChange = S({ Volume = 0.45, Fallback = { B.Click, 0.65 }, RollOff = { 4, 30 } }),
	Interference = S({ Volume = 0.35, Pitch = { 0.7, 1.1 }, Fallback = { B.Click, 0.16 }, RollOff = { 3, 25 } }),
}

---------------------------------------------------------------------------
-- NIGHT VISION ("BEEP - WHIRR")
---------------------------------------------------------------------------
SoundConfig.NightVision = {
	Equip = S({ Volume = 0.4, Fallback = { B.Unsheath, 1.9 }, RollOff = { 3, 25 } }),
	Unequip = S({ Volume = 0.35, Fallback = { B.Unsheath, 1.5 }, RollOff = { 3, 25 } }),
	PowerOn = S({ Volume = 0.55, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.35 }, RollOff = { 3, 30 } }),
	PowerOff = S({ Volume = 0.45, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.7 }, RollOff = { 3, 30 } }),
	Activation = S({ Volume = 0.35, Pitch = { 1, 1 }, Fallback = { B.Swoosh, 0.5 }, RollOff = { 3, 25 } }),
	Hum = S({ Volume = 0.1, Looped = true, Loop = "NightVisionHum", Fallback = { B.Click, 0.06 }, Spatial = false, Group = "EquipmentSFX" }),
	BatteryWarning = S({ Volume = 0.35, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.8 }, Spatial = false, Group = "UI" }),
	Static = S({ Volume = 0.35, Pitch = { 0.8, 1.2 }, Fallback = { B.Click, 0.18 }, Spatial = false }),
	SignalLoss = S({ Volume = 0.5, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.3 }, Spatial = false }),
}

---------------------------------------------------------------------------
-- GENERIC EQUIPMENT HANDLING
---------------------------------------------------------------------------
SoundConfig.Equipment = {
	Handling = S({ Volume = 0.35, Pitch = { 0.9, 1.1 }, Fallback = { B.Swoosh, 1.8 }, RollOff = { 3, 25 } }),
	Holster = S({ Volume = 0.3, Pitch = { 0.9, 1.1 }, Fallback = { B.Swoosh, 1.5 }, RollOff = { 3, 25 } }),
}

---------------------------------------------------------------------------
-- PLAYER: material footsteps, jumps, landings
---------------------------------------------------------------------------
local function step(builtinSpeed: number, volume: number?)
	return S({
		Volume = volume or 0.55,
		Pitch = { 0.9, 1.1 },
		VolumeJitter = 0.15,
		Group = "PlayerSFX",
		RollOff = { 4, 55 },
		Fallback = { B.Step, builtinSpeed },
	})
end

SoundConfig.Player = {
	Footstep = {
		Concrete = step(1),
		Wood = step(0.85),
		Metal = step(1.35, 0.6),
		Tile = step(1.15),
		Carpet = step(0.75, 0.35),
		Water = S({ Volume = 0.45, Pitch = { 0.85, 1.15 }, VolumeJitter = 0.15, Group = "PlayerSFX", RollOff = { 4, 55 }, Fallback = { B.Splash, 1.6 } }),
		Grass = step(0.7, 0.4),
		Glass = step(1.5, 0.55),
		Hospital = step(1.2),
		School = step(0.9),
	},
	Jump = S({ Volume = 0.35, Group = "PlayerSFX", RollOff = { 4, 40 }, Fallback = { B.Jump, 1 } }),
	Land = S({ Volume = 0.55, Group = "PlayerSFX", RollOff = { 5, 60 }, Fallback = { B.Land, 1 } }),
	HeavyLand = S({ Volume = 0.85, Group = "PlayerSFX", RollOff = { 6, 80 }, Fallback = { B.Land, 0.7 } }),
}

-- Footstep volume by movement mode (also used for noise, see GameConfig.Noise)
SoundConfig.StepVolume = { Sneak = 0.3, Walk = 0.6, Run = 1 }

-- Roblox material -> footstep surface. A part's "FootstepSurface" attribute overrides this.
SoundConfig.MaterialSurfaces = {
	Concrete = "Concrete",
	Asphalt = "Concrete",
	Slate = "Concrete",
	Pebble = "Concrete",
	Brick = "Concrete",
	Cobblestone = "Concrete",
	Granite = "Concrete",
	Rock = "Concrete",
	Wood = "Wood",
	WoodPlanks = "Wood",
	Metal = "Metal",
	DiamondPlate = "Metal",
	CorrodedMetal = "Metal",
	Foil = "Metal",
	Marble = "Tile",
	SmoothPlastic = "Tile",
	Plastic = "Tile",
	Fabric = "Carpet",
	Water = "Water",
	Grass = "Grass",
	LeafyGrass = "Grass",
	Ground = "Grass",
	Mud = "Grass",
	Sand = "Grass",
	Glass = "Glass",
	Ice = "Glass",
}

---------------------------------------------------------------------------
-- DOORS (one set per door type; Door attribute "DoorType" picks the set)
---------------------------------------------------------------------------
local function doorSet(pitch: number, weight: number)
	return {
		Open = S({ Volume = 0.55 * weight, Group = "PlayerSFX", RollOff = { 6, 70 }, Fallback = { B.Swoosh, 0.55 * pitch }, Noise = 0.15, NoiseKind = "DoorOpen" }),
		Close = S({ Volume = 0.4 * weight, Group = "PlayerSFX", RollOff = { 5, 55 }, Fallback = { B.Click, 0.6 * pitch }, Noise = 0.08, NoiseKind = "DoorClose" }),
		Slam = S({ Volume = 1, Group = "PlayerSFX", RollOff = { 10, 160 }, Fallback = { B.Click, 0.3 * pitch }, Noise = 0.6, NoiseKind = "DoorSlam" }),
		Locked = S({ Volume = 0.55 * weight, Group = "PlayerSFX", RollOff = { 5, 50 }, Fallback = { B.Click, 1.3 * pitch }, Noise = 0.1, NoiseKind = "Interaction" }),
		Handle = S({ Volume = 0.35, Group = "PlayerSFX", RollOff = { 4, 35 }, Fallback = { B.Click, 1.6 * pitch } }),
		Creak = S({ Volume = 0.45 * weight, Pitch = { 0.85, 1.15 }, Group = "PlayerSFX", RollOff = { 6, 70 }, Fallback = { B.Groan, 1.6 * pitch }, Noise = 0.1, NoiseKind = "DoorOpen" }),
	}
end

SoundConfig.Door = {
	Wood = doorSet(1, 0.9),
	Metal = doorSet(0.8, 1),
	Security = doorSet(0.65, 1.1), -- Mall Security Door
	Hospital = doorSet(1.1, 0.9),
	School = doorSet(0.95, 0.9),
	Motel = doorSet(0.9, 0.95),
	Locker = doorSet(1.3, 0.7),
}

---------------------------------------------------------------------------
-- PLAYER INTERACTIONS
---------------------------------------------------------------------------
local function interaction(builtin: string, speed: number, volume: number?, noise: number?, spatial: boolean?)
	return S({
		Volume = volume or 0.55,
		Group = "PlayerSFX",
		RollOff = { 4, 45 },
		Fallback = { builtin, speed },
		Noise = noise,
		NoiseKind = if noise then "Interaction" else nil,
		Spatial = if spatial == nil then true else spatial,
	})
end

SoundConfig.Interaction = {
	BatteryPickup = interaction(B.Click, 0.9, 0.55, 0.04),
	BatteryUse = interaction(B.Click, 0.7, 0.5, 0.04),
	EvidenceCollect = interaction(B.Ping, 1.4, 0.55, nil, false),
	Upgrade = interaction(B.Ping, 1.6, 0.6, nil, false),
	Purchase = interaction(B.Ping, 1.2, 0.6, nil, false),
	LockerOpen = interaction(B.Click, 0.45, 0.6, 0.18),
	LockerClose = interaction(B.Click, 0.35, 0.6, 0.2),
	DrawerOpen = interaction(B.Swoosh, 0.9, 0.5, 0.08),
	DrawerClose = interaction(B.Click, 0.55, 0.5, 0.1),
	ElevatorButton = interaction(B.Click, 1.5, 0.45, 0.05),
	ElevatorDing = S({ Volume = 0.7, Group = "PlayerSFX", RollOff = { 8, 110 }, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.95 }, Noise = 0.2, NoiseKind = "Interaction" }),
	Computer = interaction(B.Ping, 2, 0.4, 0.05),
	KeyPickup = interaction(B.Click, 1.8, 0.55, 0.03),
	Unlock = interaction(B.Click, 0.75, 0.6, 0.1),
	GeneratorStart = S({ Volume = 0.9, Group = "PlayerSFX", RollOff = { 10, 150 }, Fallback = { B.Groan, 0.35 }, Noise = 0.5, NoiseKind = "Interaction" }),
	BreakerOn = interaction(B.Click, 0.4, 0.8, 0.35),
	BreakerOff = interaction(B.Click, 0.35, 0.8, 0.35),
	RadioStatic = S({ Volume = 0.6, Group = "Voice", RollOff = { 6, 80 }, Pitch = { 0.9, 1.1 }, Fallback = { B.Click, 0.2 }, Noise = 0.25, NoiseKind = "Radio" }),
	RadioVoice = S({ Volume = 0.55, Group = "Voice", RollOff = { 6, 70 }, Fallback = { B.Groan, 0.7 }, Noise = 0.2, NoiseKind = "Radio" }),
	PhoneRing = S({ Volume = 0.8, Group = "AnomalySFX", RollOff = { 10, 140 }, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.9 }, Noise = 0.3, NoiseKind = "Phone" }),
	PhonePickup = interaction(B.Click, 0.8, 0.55, 0.06),
	Revive = interaction(B.GetUp, 1, 0.6, 0.1),
}

---------------------------------------------------------------------------
-- ANOMALIES
---------------------------------------------------------------------------
local function anomaly(builtin: string, speed: number, volume: number?, rollOff: { number }?, pitch: { number }?)
	return S({
		Volume = volume or 0.6,
		Group = "AnomalySFX",
		RollOff = rollOff or { 6, 70 },
		Pitch = pitch or { 0.9, 1.1 },
		Fallback = { builtin, speed },
	})
end

SoundConfig.Anomaly = {
	Sting = anomaly(B.Ping, 0.25, 0.45),
	Vanish = anomaly(B.Swoosh, 0.45, 0.5),
	ClockTick = anomaly(B.Click, 1.8, 0.4, { 4, 50 }, { 0.98, 1.02 }),
	DoorCreak = anomaly(B.Groan, 1.5, 0.5),
	Whisper = anomaly(B.Groan, 1.9, 0.35, { 3, 40 }),
	Scratch = anomaly(B.Swoosh, 0.7, 0.45, { 4, 50 }),
	Knock = anomaly(B.Click, 0.4, 0.7, { 6, 90 }),
	Skitter = anomaly(B.Click, 2.5, 0.5, { 4, 60 }),
	Groan = anomaly(B.Groan, 0.55, 0.55, { 6, 80 }),
	ObserverDrone = anomaly(B.Groan, 0.2, 0.9, { 60, 500 }, { 1, 1 }),
	NightManagerChime = anomaly(B.Ping, 0.7, 0.9, { 60, 600 }, { 1, 1 }),
	PhotographerFlash = anomaly(B.Click, 0.7, 0.9, { 8, 90 }),
	ListenerBreath = S({ Volume = 0.45, Group = "AnomalySFX", Looped = true, Loop = "ListenerBreath", RollOff = { 4, 45 }, Fallback = { B.Groan, 0.3 } }),
	ListenerAlert = anomaly(B.Click, 0.35, 0.8, { 6, 90 }),
	ListenerAttack = S({ Volume = 1, Group = "Jumpscares", Spatial = false, Pitch = { 0.95, 1.05 }, Fallback = { B.Groan, 0.45 } }),
	LightCreatureHiss = anomaly(B.Swoosh, 0.35, 0.6, { 5, 60 }),
	LightCreatureShriek = anomaly(B.Groan, 1.4, 0.9, { 8, 120 }),
	EchoWhisper = anomaly(B.Groan, 1.7, 0.45, { 4, 55 }),
	EchoVoice = anomaly(B.Groan, 1.2, 0.5, { 4, 60 }),
	MimicGiggle = anomaly(B.Groan, 2.2, 0.4, { 4, 45 }),
	Jumpscare = S({ Volume = 1, Group = "Jumpscares", Spatial = false, Pitch = { 1, 1 }, Fallback = { B.Groan, 0.6 } }),
	-- ceiling crawler + creatures
	CeilingCreak = anomaly(B.Groan, 1.9, 0.55, { 5, 55 }),
	CeilingScuttle = anomaly(B.Click, 1.6, 0.65, { 5, 60 }),
	DustFall = anomaly(B.Swim, 2.5, 0.35, { 3, 30 }),
	Breath = anomaly(B.Wind, 0.6, 0.45, { 3, 28 }),
	Snap = anomaly(B.Click, 0.9, 0.6, { 4, 50 }),
	Teleport = anomaly(B.Swoosh, 0.5, 0.55, { 5, 60 }),
	Laugh = anomaly(B.Groan, 1.6, 0.55, { 6, 80 }),
	Thud = anomaly(B.Land, 0.6, 0.8, { 6, 90 }),
	GlassTap = anomaly(B.Click, 2.2, 0.5, { 4, 45 }),
	-- object anomalies
	CartRoll = anomaly(B.Step, 0.6, 0.55, { 5, 60 }),
	ChairScrape = anomaly(B.Swoosh, 0.35, 0.6, { 5, 60 }),
	ShelfCrash = anomaly(B.Land, 0.4, 1, { 10, 140 }),
	BallBounce = anomaly(B.Land, 1.8, 0.5, { 4, 50 }),
	BagRustle = anomaly(B.Swoosh, 1.4, 0.4, { 3, 30 }),
	MetalGroan = anomaly(B.Groan, 0.3, 0.7, { 10, 140 }),
	ArcadeJingle = anomaly(B.Ping, 1.3, 0.5, { 5, 60 }, { 0.97, 1.03 }),
	TVOn = anomaly(B.Click, 0.25, 0.5, { 4, 45 }),
	CarAlarm = S({ Volume = 0.8, Group = "AnomalySFX", Looped = true, Loop = "CarAlarm", RollOff = { 15, 220 }, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.8 } }),
	StoreAlarm = S({ Volume = 0.7, Group = "AnomalySFX", Looped = true, Loop = "StoreAlarm", RollOff = { 12, 180 }, Pitch = { 1, 1 }, Fallback = { B.Ping, 1.6 } }),
	TVStatic = S({ Volume = 0.35, Group = "AnomalySFX", Looped = true, Loop = "TVStatic", RollOff = { 3, 35 }, Fallback = { B.Wind, 2.4 } }),
	EntityDrone = S({ Volume = 0.5, Group = "AnomalySFX", Looped = true, Loop = "EntityDrone", RollOff = { 6, 60 }, Pitch = { 1, 1 }, Fallback = { B.Wind, 0.3 } }),
}

---------------------------------------------------------------------------
-- JUMPSCARES (2D, always first person). Every major anomaly has its own.
---------------------------------------------------------------------------
local function scare(builtin: string, speed: number, volume: number?)
	return S({ Volume = volume or 1, Group = "Jumpscares", Spatial = false, Pitch = { 0.97, 1.03 }, VolumeJitter = 0, Fallback = { builtin, speed } })
end

SoundConfig.Jumpscare = {
	Impact = scare(B.Land, 0.45),
	Screech = scare(B.Groan, 1.8, 0.9),
	CrawlerDrop = scare(B.Land, 0.6),
	CrawlerScreech = scare(B.Groan, 2.2, 0.95),
	Titan = scare(B.Groan, 0.35),
	Smile = scare(B.Groan, 1.4, 0.9),
	Possessed = scare(B.Groan, 1.1, 0.95),
	Slacker = scare(B.Groan, 0.7, 0.9),
	Static = scare(B.Wind, 3, 0.7),
	Ringing = scare(B.Ping, 2.6, 0.35),
	Fall = scare(B.Land, 0.8, 0.8),
}

---------------------------------------------------------------------------
-- ENVIRONMENT + AMBIENCE + MUSIC
---------------------------------------------------------------------------
SoundConfig.Environment = {
	Thunder = S({ Volume = 0.9, Group = "Ambience", Spatial = false, Pitch = { 0.85, 1.1 }, Fallback = { B.Groan, 0.12 } }),
	LightningCrack = S({ Volume = 0.6, Group = "Ambience", Spatial = false, Fallback = { B.Click, 0.25 } }),
	HVACBurst = S({ Volume = 0.8, Group = "Ambience", RollOff = { 15, 140 }, Fallback = { B.Swoosh, 0.25 }, Occlusion = true }),
	DistantBang = S({ Volume = 0.8, Group = "Ambience", RollOff = { 20, 250 }, Fallback = { B.Click, 0.3 } }),
	Drip = S({ Volume = 0.3, Group = "Ambience", RollOff = { 3, 40 }, Pitch = { 0.8, 1.3 }, Fallback = { B.Ping, 3 } }),
	PAStatic = S({ Volume = 0.5, Group = "Ambience", Spatial = false, Fallback = { B.Click, 0.18 } }),
	PAChime = S({ Volume = 0.6, Group = "Ambience", Spatial = false, Pitch = { 1, 1 }, Fallback = { B.Ping, 0.8 } }),
	LightBuzz = S({ Volume = 0.45, Group = "Ambience", RollOff = { 3, 35 }, Fallback = { B.Click, 0.15 } }),
}

SoundConfig.Ambience = {
	MallHum = S({ Volume = 0.3, Group = "Ambience", Spatial = false, Looped = true, Loop = "MallHum", Fallback = { B.Wind, 0.3 } }),
	RainSkylight = S({ Volume = 0.45, Group = "Ambience", Spatial = false, Looped = true, Loop = "RainSkylight", Fallback = { B.Swim, 0.55 } }),
	HVAC = S({ Volume = 0.35, Group = "Ambience", Spatial = false, Looped = true, Loop = "HVAC", Fallback = { B.Wind, 0.55 } }),
}

SoundConfig.Music = {
	-- until the Loops bank is uploaded: a slowed-down wind drone
	Lobby = S({ Volume = 0.5, Group = "Music", Spatial = false, Looped = true, Loop = "MusicLobby", Fallback = { B.Wind, 0.35 } }),
	Tension = S({ Volume = 0.5, Group = "Music", Spatial = false, Looped = true, Loop = "MusicTension", Fallback = { B.Wind, 0.22 } }),
}

---------------------------------------------------------------------------
-- UI
---------------------------------------------------------------------------
local function ui(builtin: string, speed: number, volume: number?)
	return S({ Volume = volume or 0.5, Group = "UI", Spatial = false, Pitch = { 1, 1 }, VolumeJitter = 0, Fallback = { builtin, speed } })
end

SoundConfig.UI = {
	Button = ui(B.Click, 1.3, 0.35),
	Toast = ui(B.Ping, 1.5, 0.3),
	Announce = ui(B.Ping, 0.7, 0.6),
	Reveal = ui(B.Ping, 0.35, 0.9),
	NewDiscovery = ui(B.Ping, 1.6, 0.7),
	Fail = ui(B.Click, 0.5, 0.35),
	Whisper = ui(B.Groan, 1.8, 0.35),
	Heartbeat = ui(B.Click, 0.4, 0.5),
	Error = ui(B.Ping, 0.4, 0.45),
	Stinger = ui(B.Groan, 0.4, 0.8),
	QueueJoin = ui(B.Ping, 1.3, 0.45),
	QueueLeave = ui(B.Ping, 0.9, 0.4),
	QueueTick = ui(B.Click, 1.8, 0.3),
	QueueTickFinal = ui(B.Ping, 1.7, 0.45),
	Terminal = ui(B.Click, 2.2, 0.4),
	MissionStart = ui(B.Land, 0.5, 0.8),
}

---------------------------------------------------------------------------
-- ACOUSTICS: reverb + ambience beds per zone, and per-map "feel"
---------------------------------------------------------------------------
SoundConfig.ZoneAcoustics = {
	Entrance = { Reverb = Enum.ReverbType.Hallway, Beds = { "Ambience.MallHum", "Ambience.RainSkylight" } },
	GrandHall = { Reverb = Enum.ReverbType.Hangar, Beds = { "Ambience.MallHum", "Ambience.RainSkylight" } },
	Supermarket = { Reverb = Enum.ReverbType.Arena, Beds = { "Ambience.MallHum" } },
	Electronics = { Reverb = Enum.ReverbType.Room, Beds = { "Ambience.MallHum" } },
	Clothing = { Reverb = Enum.ReverbType.Room, Beds = { "Ambience.MallHum" } },
	Restrooms = { Reverb = Enum.ReverbType.Bathroom, Beds = { "Ambience.HVAC" } },
	Cinema = { Reverb = Enum.ReverbType.Auditorium, Beds = { "Ambience.MallHum" } },
	Theaters = { Reverb = Enum.ReverbType.Auditorium, Beds = {} },
	Arcade = { Reverb = Enum.ReverbType.CarpettedHallway, Beds = { "Ambience.MallHum" } },
	ToyStore = { Reverb = Enum.ReverbType.Room, Beds = { "Ambience.MallHum" } },
	BookNook = { Reverb = Enum.ReverbType.PaddedCell, Beds = {} },
	FoodCourt = { Reverb = Enum.ReverbType.ConcertHall, Beds = { "Ambience.MallHum", "Ambience.RainSkylight" } },
	ServiceHalls = { Reverb = Enum.ReverbType.StoneCorridor, Beds = { "Ambience.HVAC" } },
	BackOfHouse = { Reverb = Enum.ReverbType.StoneRoom, Beds = { "Ambience.HVAC" } },
	SecurityRoom = { Reverb = Enum.ReverbType.Room, Beds = { "Ambience.HVAC" } },
	ParkingGarage = { Reverb = Enum.ReverbType.ParkingLot, Beds = { "Ambience.HVAC" } },
	Lobby = { Reverb = Enum.ReverbType.LivingRoom, Beds = { "Ambience.RainSkylight" }, Music = "Music.Lobby" },
	DarkRoom = { Reverb = Enum.ReverbType.PaddedCell, Beds = {} },
}

--[[
	Map-specific equipment feel. The Dead Mall is implemented; the others are
	ready for future maps (set Workspace.Map:SetAttribute("MapId", "Motel")).
	  NoiseCarry       multiplier on how far player noise travels to anomalies
	  MetalCarry       extra multiplier for metal-surface / metal-equipment noise
	  BaseMasking      constant environmental noise (rain) that hides quiet sounds
	  DefaultReverb    reverb outside named zones
]]
SoundConfig.MapAcoustics = {
	DeadMall = { NoiseCarry = 1.1, MetalCarry = 1.1, BaseMasking = 0, DefaultReverb = Enum.ReverbType.Hangar },
	Hospital = { NoiseCarry = 1.25, MetalCarry = 1.4, BaseMasking = 0, DefaultReverb = Enum.ReverbType.Hallway },
	School = { NoiseCarry = 1.1, MetalCarry = 1.3, BaseMasking = 0, DefaultReverb = Enum.ReverbType.Hallway },
	Motel = { NoiseCarry = 0.9, MetalCarry = 1, BaseMasking = 0.12, DefaultReverb = Enum.ReverbType.ParkingLot },
}
SoundConfig.CurrentMap = "DeadMall"

---------------------------------------------------------------------------
-- Lookup helpers (no need to edit below)
---------------------------------------------------------------------------

local CATEGORIES = { "Camera", "Flashlight", "EMF", "Thermal", "UV", "NightVision", "Equipment", "Player", "Door", "Interaction", "Anomaly", "Jumpscare", "Environment", "Ambience", "Music", "UI" }
SoundConfig.Categories = CATEGORIES

local byPath = {}

local function register(prefix: string, node)
	for key, value in pairs(node) do
		if type(value) == "table" then
			local path = prefix .. "." .. key
			if value.Group ~= nil and value.Volume ~= nil then
				value.Path = path
				byPath[path] = value
			else
				register(path, value)
			end
		end
	end
end

for _, category in ipairs(CATEGORIES) do
	register(category, SoundConfig[category])
end

function SoundConfig.Get(path: string)
	return byPath[path]
end

function SoundConfig.AllPaths(): { string }
	local list = {}
	for path in pairs(byPath) do
		table.insert(list, path)
	end
	table.sort(list)
	return list
end

return SoundConfig
